[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[rpc_endpoints]
educhain-testnet = "https://rpc.open-campus-codex.gelato.digital"

[etherscan]
educhain-testnet = { key = "xxx", url = "https://edu-chain-testnet.blockscout.com/api" }
# Chain configurations
[profile.chains.656476] # EDU Chain Testnet
name = "educhain-testnet"
chain_id = 656476
explorer = "https://edu-chain-testnet.blockscout.com"
currency = "EDU"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
